version: 0.2

phases:
  install:
    commands:
      - echo "✅ INSTALL PHASE"
      - npm install

  build:
    commands:
      - echo "✅ BUILD PHASE"
      - zip -r app.zip . -x "node_modules/*" ".git/*" "README.md" "template.yaml" "test.txt" "tet"
      - echo "🧪 Contents of current dir:"
      - ls -la

artifacts:
  files:
    - app.zip
  discard-paths: yes # 👈 ensures app.zip goes to root
  base-directory: . # 👈 important: ensures it picks from the right place
