version: 0.2

phases:
  install:
    commands:
      - echo "✅ INSTALL PHASE"
      - npm install

  build:
    commands:
      - echo "✅ BUILD PHASE"
      - cd ./$BUILD_DIRECTORY
      - zip -r output.zip . -x ".git/*" "README.md" "template.yaml" "test.txt" "node_modules/*"
      - echo "🧪 Contents of current dir:"
      - ls
      - echo "📦 Verifying output.zip:"
      - unzip -l output.zip

artifacts:
  base-directory: $BUILD_DIRECTORY
  files:
    - output.zip
